### ISSUE TITLE
Wizard flashes if setState is called within currentStep callback

### ISSUE THREAD

**Issue by Puupuls** [talut/react-native-wizard#13]
If the state is updated inside currentStep, then component reloads before starting next slide animation and it shows as 

next screen appears ->  everything flashes in background color -> next screen slides in

To reproduce:

```
currentStep={({ currentStep, isLastStep, isFirstStep }) => {
    this.setState({
        indexPage: currentStep
    });
}}
```

and use something state dependant inside one of the steps

**Comment by talut** [comment]
```
 currentStep={({ currentStep, isLastStep, isFirstStep }) => {
            setCurrentStep(currentStep)
          }}
```

I can't reproduce any flash.  I'm updating state with setCurrentStep

**Comment by monkin77** [comment]
Same thing happened to me. The only workaround I found was wrapping my components in a component that ignored the first render as such:
`import React, {useEffect, useState} from 'react';
import {View} from 'react-native';

/**
 * This wrapper is needed since the animation in the Wizard was flashing on the 1st render
 * @param {*} param0
 * @returns
 */
const StepWrapper = ({children}) => {
  const [show, setShow] = useState(false);

  useEffect(() => {
    setShow(true);
  }, []);

  return show ? <View>{children}</View> : <View />;
};
export default StepWrapper;`
